spring:
  application:
    name: SimpleStockMarket
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html
  api-docs:
    enabled: false # Disable automatic scanning, keep it "Contract-First"
